version: '3.8'

services:
  user-auth:
    image: nivaldeir/user-authentication:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - public
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ORIGIN: "taticca.nivaldeirsoft.com.br"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET_ID: ${GOOGLE_CLIENT_SECRET_ID}
      PORT: 8081
      URL: ${API_URL_AUTH}
      CLIENT_URL_SUCCESS: "/"
      CLIENT_URL_ERROR: "/login"
      RABBIT_MQ_HOST: 'amqp://rabbitmq'
      JWT_SECRET: "123456"
    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: "0.2"
    #       memory: 100M
    #   placement:
    #     constraints:
    #       - node.role == manager
    #   labels:
    #     - traefik.enable=true
    #     - traefik.http.routers.auth.rule=Host(`auth.nivaldeirsoft.com.br`)
    #     - traefik.http.routers.auth.entrypoints=websecure
    #     - traefik.http.routers.auth.tls.certresolver=le
    #     - traefik.http.routers.auth.service=auth
    #     - traefik.http.services.auth.loadbalancer.server.port=8081
networks:
  public:
    driver: bridge
