apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nivaldeir/user-autenticacao:{{TAG}}
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: WSRS_DATABASE_USER
            value: postgres-service
          - name: WSRS_DATABASE_PASSWORD
            value: postgres
          - name: WSRS_DATABASE_NAME
            value: postgres
          - name: WSRS_DATABASE_PORT
            value: "5432"
          - name: WSRS_DATABASE_HOST
            value: admin
          - name: CLIENT_URL_SUCCESS
            value: "/"
          - name: CLIENT_URL_ERROR
            value: "/login"
          - name: RABBIT_MQ_HOST
            value: "amqp://localhost"
          - name: JWT_SECRET
            value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        resources: {}
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
